# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form Validation.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 656)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(90, 380, 51, 20))
        self.label_6.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.comboBox_gender = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_gender.setGeometry(QtCore.QRect(150, 380, 91, 22))
        self.comboBox_gender.setObjectName("comboBox_gender")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.setItemText(0, "")
        self.comboBox_gender.addItem("")
        self.comboBox_gender.addItem("")
        self.comboBox_education = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_education.setGeometry(QtCore.QRect(150, 410, 211, 22))
        self.comboBox_education.setObjectName("comboBox_education")
        self.comboBox_education.addItem("")
        self.comboBox_education.setItemText(0, "")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.comboBox_education.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(80, 410, 61, 20))
        self.label_7.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(150, 480, 71, 28))
        self.btn_save.setObjectName("btn_save")
        self.btn_clear = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear.setGeometry(QtCore.QRect(320, 480, 71, 28))
        self.btn_clear.setObjectName("btn_clear")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(580, 10, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(580, 30, 161, 16))
        self.label_9.setObjectName("label_9")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(90, 210, 55, 16))
        self.label_5.setObjectName("label_5")
        self.textEdit_address = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_address.setGeometry(QtCore.QRect(150, 210, 250, 160))
        self.textEdit_address.setMinimumSize(QtCore.QSize(250, 160))
        self.textEdit_address.setObjectName("textEdit_address")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(50, 90, 235, 111))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit_email = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.gridLayout.addWidget(self.lineEdit_email, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.lineEdit_age = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_age.setObjectName("lineEdit_age")
        self.gridLayout.addWidget(self.lineEdit_age, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btn_save.clicked.connect(self.prosesValidasi)
        self.btn_clear.clicked.connect(self.kosongkanInput)

        QtWidgets.QShortcut(QtGui.QKeySequence("Q"), MainWindow, activated=MainWindow.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Form Validation"))
        self.label_6.setText(_translate("MainWindow", "Gender:"))
        self.comboBox_gender.setItemText(1, _translate("MainWindow", "Male"))
        self.comboBox_gender.setItemText(2, _translate("MainWindow", "Female"))
        self.comboBox_education.setItemText(1, _translate("MainWindow", "Elementary School"))
        self.comboBox_education.setItemText(2, _translate("MainWindow", "Junior High School"))
        self.comboBox_education.setItemText(3, _translate("MainWindow", "Senior High School"))
        self.comboBox_education.setItemText(4, _translate("MainWindow", "Diploma"))
        self.comboBox_education.setItemText(5, _translate("MainWindow", "Bachelor's Degree"))
        self.comboBox_education.setItemText(6, _translate("MainWindow", "Master's Degree"))
        self.comboBox_education.setItemText(7, _translate("MainWindow", "Doctoral Degree"))
        self.label_7.setText(_translate("MainWindow", "Education:"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.label_8.setText(_translate("MainWindow", "Nama: Adina Ayu Daraswita"))
        self.label_9.setText(_translate("MainWindow", "NIM: F1D022030"))
        self.label_5.setText(_translate("MainWindow", "Address:"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Email:"))
        self.label_3.setText(_translate("MainWindow", "Age:"))
        self.label_4.setText(_translate("MainWindow", "Phone Number:"))
        self.lineEdit_phone.setInputMask(_translate("MainWindow", "+62 000 0000 0000"))

    def prosesValidasi(self):
        name = self.lineEdit_name.text().strip()
        email = self.lineEdit_email.text().strip()
        age = self.lineEdit_age.text().strip()
        phone = self.lineEdit_phone.text().strip()
        address = self.textEdit_address.toPlainText().strip()
        gender = self.comboBox_gender.currentText()
        education = self.comboBox_education.currentText()

        # Validasi 
        if not name or name.isnumeric():
            self.peringatan("Name harus diisi dan tidak boleh berupa angka.")
            return
        if name == "":
            self.peringatan("Isi dulu dong nama kamu~")
            return
        elif name.isnumeric():
            self.peringatan("Nama nggak boleh cuma angka yaa.")
            return

        if not email:
            self.peringatan("Email tidak boleh kosong.")
            return
        if not re.fullmatch(r"[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+", email):
            self.peringatan("Format email tidak valid.")
            return
        if not age:
            self.peringatan("Age tidak boleh kosong.")
            return
        if not age.isdigit():
            self.peringatan("Age harus berupa angka.")
            return
        if not re.match(r"^\+62 \d{3} \d{4} \d{4}$", phone):
            self.peringatan("Phone harus sesuai format +62 000 0000 0000.")
            return
        if not address:
            self.peringatan("Address wajib diisi.")
            return
        if gender == "":
            self.peringatan("Gender wajib dipilih.")
            return
        if education == "":
            self.peringatan("Education wajib dipilih.")
            return

        if int(age) < 10:
            self.peringatan("Kamu terlalu muda untuk isi form ini")
            return

        QtWidgets.QMessageBox.information(None, "Success", "Data berhasil disimpan!")
        self.kosongkanInput()

    def peringatan(self, msg):
        QtWidgets.QMessageBox.warning(None, "Warning", msg)

    def kosongkanInput(self):
        self.lineEdit_name.clear()
        self.lineEdit_email.clear()
        self.lineEdit_age.clear()
        self.lineEdit_phone.clear()
        self.textEdit_address.clear()
        self.comboBox_gender.setCurrentIndex(0)
        self.comboBox_education.setCurrentIndex(0)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
